### PR TITLE
Disable logs when localStorage is not available

### PR DESCRIPTION
**Pull request by latentflip**
It occurred to me after merging and testing https://github.com/latentflip/bows/pull/33 that if localStorage is unavailable we'd rather fall back to not logging rather than logging everything. This obviously means devs can't enable logging when localStorage is unavailable, but that feels preferable to users getting all the logs.

Thoughts @Jones-S @d-simon?

### CODE REVIEW

**Comment by Jones-S** [comment]
Yeah makes sense I guess. The dev will definitely realize that he has to enable localStorage...
👍🏼

**Comment by Jones-S** [comment]
I guess I will maybe have to adjust some code within our wrapper, but that's fine...

**Comment by latentflip** [comment]
> I guess I will maybe have to adjust some code within our wrapper, but that's fine...

Can you explain a little more here. Want to be sure this change is going to work for you.

**Comment by Jones-S** [comment]
I just saying that I will have to test it on my side quickly. I don't know by heart if our wrapper somehow relies on the fact that something has to be logged. Maybe it is all fine.
Is it OK, if I try it in ~ 1.5h and get back to you after?

**Comment by latentflip** [comment]
@Jones-S :+1: sure thing. I would guess it's fine, as the behaviour here when localStorage is unavailable for a user, would be exactly the same as when a user has localStorage available but doesn't have `localStorage.debug` set. I.e. we won't log anything to the console.

**Comment by Jones-S** [comment]
Ok, then I assume that it is probably no problem. If you want to rerelease, you can also do it now. I can adjust our wrapper after, if necessary. Especially when the chance of breaking is small.

**Comment by latentflip** [comment]
@Jones-S all good, I can wait, let me know.

**Comment by Jones-S** [comment]
Sorry I had to see how a stranded ship got pulled back into sea again :)
Took longer than expected.

😅
I will check it out now. 👍

**Comment by Jones-S** [comment]
Alright. I copied your new code into an existing project, and it looks all fine 👍.
The logs are just gone, no error whatsoever.
So it's good to ship (like above ⛴) 😄

**Pull request merged**
