### PR TITLE
Bugfix/andlogkey check

### PR DESCRIPTION
**Pull request by Jones-S**
Hey @latentflip 

I started with this and realized that we have to fix another upstream dependency as well.
This PR: https://github.com/HenrikJoreteg/andlog/pull/10
Should be merged first, because `andlog` does try to read `ls.andlogKey` as well.
I added some tests if `ls` exists there and here.

As I said we have a few pages, which broke when the user disabled localStorage (cookies).
Now they would still work, just without the possibility to set a custom logKey.

Tell me if I have forgotten something.

Also this PR already includes https://github.com/latentflip/bows/pull/30, because it addresses the same issue.

I can squash my commits, if you'd like.

### CODE REVIEW

**Comment by Jones-S** [comment]
Yeah true. Sorry I was using yarn out of habit. I will remove it and we wait for the dependency...
Cheers

**Comment by Jones-S** [comment]
The dependency was updated and I pushed a commit using the newer version. Should be ready to merge.

**Comment by Jones-S** [comment]
@latentflip do you have an estimate, when you can have a look at this?
Depending on that I would either include your updated version or my fork into a project I am working on.
Cheers

**Comment by latentflip** [comment]
@Jones-S I'll get to it today hopefully. I couldn't get the old tests to run properly so I was going to try and revive them to get a bit of coverage - it's been a while!

**Comment by Jones-S** [comment]
Sounds awesome. Thank you. Hope you can get them to work 🥴

**Comment by latentflip** [comment]
@Jones-S skipped the tests for today so 🤞 it's all good. Published as 1.7.1

**Comment by Jones-S** [comment]
Haha, alrighty. Let's hope for the best. Thanks

**Pull request merged**
