### PR TITLE
Show the time diff since bows was last called (similar to debug)

### PR DESCRIPTION
**Pull request by asleepysamurai**
I recently switched over from debug to bows, and ended up missing the time difference feature of debug too much. I also noticed that there was an open suggestion for this feature (#17 ), so I have implemented this for bows. Please have a look and let me know if this can be merged into bows.

### CODE REVIEW

**Comment by asleepysamurai** [comment]
And I have no idea hwo to write tests that might pass since the time diff would vary each time, and hence expected logs might never match actual logs. Any suggestions?

**Comment by latentflip** [comment]
Hey I'm interested in this feature, but since you've reformatted everything I can't easily tell what's changed?

Any chance of fixing the PR without the reformatting?

Thanks!

**Comment by asleepysamurai** [comment]
Sorry bout that. Forgot I had sublime set to beautify on save. Should be all cleaned up now.

**Comment by asleepysamurai** [comment]
Looks like this breaks the 'show file name where bows was invoked in console' feature. Will fix and get back to you.

**Comment by latentflip** [comment]
Oh hmm yeah, I suspect that is almost certainly going to be impossible unless things have changed a lot in browsers. The only way to avoid it changing the location is to bind arguments instead of wrapping functions, and that means the bound args have to be fixed.

Philip Roberts

**Comment by asleepysamurai** [comment]
Yeah beginning to look like I didn't think this through. Will give it a shot though. Might be some hack exists, that would allow us to do this.

**Comment by asleepysamurai** [comment]
I've got something that works in Node but unfortunately not on the browser. A tiny (backwards incompatible) API change will allow it to work in the browser, but I'm not really sure if breaking compatibility is worth it.

**Comment by latentflip** [comment]
Can you gist/point at the change?

Philip Roberts

**Comment by asleepysamurai** [comment]
Okay, I have committed a change which would work on the browser and on node. However the calling API now changes from:
```
var debug = require('bows)('namespace');
debug('debug msg');
```

to:
```
var debug = require('bows)('namespace');
debug('debug msg')();
```

The method that works only in node, involves createing a custom constructor function with a prototype method `inspect`. The `inspect` method would return the diff as a string. An instance of this is then bound to the logger along with the other bound arguments. Since node's console will use the custom `inspect` method if it is available on an object, this would allow us to print out the time difference.

**Comment by asleepysamurai** [comment]
Closing this request, since it appears to be impossible to achieve this without changing the log method signature. Also, I've since learnt that the time delta between log calls is not really all that useful.

**Pull request closed without merging**
